name: PermissionWhitelist
author: LaxWasHere
version: 0.2
main: net.lazlecraft.permissionwhitelist.PermissionWhitelist
commands:
    permissionwhitelist:
        description: PermissionWhitelist commands
        aliases: pwl