name: PermissionWhitelist
author: LaxWasHere
version: 0.2
main: net.lazlecraft.permissionwhitelist.PermissionWhitelist
commands:
    wermissionwhitelist:
        description: PermissionWhitelist commands
        aliases: pw